/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sstravels;

/**
 *
 * @author LENOVO
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        this.setBounds(100,50,1210,710);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.setToolTipText("");
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 0, 110, 120);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("GetTicket");
        jPanel1.add(jButton2);
        jButton2.setBounds(1090, 0, 110, 120);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Contact");
        jPanel1.add(jButton3);
        jButton3.setBounds(980, 0, 110, 120);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("About");
        jPanel1.add(jButton4);
        jButton4.setBounds(870, 0, 110, 120);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Gellary");
        jPanel1.add(jButton5);
        jButton5.setBounds(760, 0, 110, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sstravels/13.PNG"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1200, 120);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Driver");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(240, 50, 100, 40);

        jRadioButton1.setText("A4");
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(290, 140, 50, 25);

        jRadioButton2.setText("B4");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(290, 180, 43, 25);

        jRadioButton3.setText("A2");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(70, 140, 107, 25);

        jRadioButton4.setText("A3");
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(220, 140, 107, 25);

        jRadioButton5.setText("A1");
        jPanel2.add(jRadioButton5);
        jRadioButton5.setBounds(10, 140, 43, 25);

        jRadioButton6.setText("J2");
        jPanel2.add(jRadioButton6);
        jRadioButton6.setBounds(70, 520, 41, 25);

        jRadioButton7.setText("B2");
        jPanel2.add(jRadioButton7);
        jRadioButton7.setBounds(70, 180, 43, 25);

        jRadioButton8.setText("J4");
        jPanel2.add(jRadioButton8);
        jRadioButton8.setBounds(290, 520, 41, 25);

        jRadioButton9.setText("B1");
        jPanel2.add(jRadioButton9);
        jRadioButton9.setBounds(10, 180, 43, 25);

        jRadioButton10.setText("J1");
        jPanel2.add(jRadioButton10);
        jRadioButton10.setBounds(10, 520, 41, 25);

        jRadioButton12.setText("H1");
        jPanel2.add(jRadioButton12);
        jRadioButton12.setBounds(10, 470, 43, 25);

        jRadioButton13.setText("G1");
        jPanel2.add(jRadioButton13);
        jRadioButton13.setBounds(10, 420, 43, 25);

        jRadioButton14.setText("F1");
        jPanel2.add(jRadioButton14);
        jRadioButton14.setBounds(10, 370, 43, 25);

        jRadioButton15.setText("E1");
        jPanel2.add(jRadioButton15);
        jRadioButton15.setBounds(10, 320, 43, 25);

        jRadioButton16.setText("D1");
        jPanel2.add(jRadioButton16);
        jRadioButton16.setBounds(10, 270, 43, 25);

        jRadioButton11.setText("C1");
        jPanel2.add(jRadioButton11);
        jRadioButton11.setBounds(10, 220, 43, 25);

        jRadioButton17.setText("C2");
        jPanel2.add(jRadioButton17);
        jRadioButton17.setBounds(70, 220, 43, 25);

        jRadioButton18.setText("D2");
        jPanel2.add(jRadioButton18);
        jRadioButton18.setBounds(70, 270, 43, 25);

        jRadioButton19.setText("E2");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton19);
        jRadioButton19.setBounds(70, 320, 43, 25);

        jRadioButton20.setText("F2");
        jRadioButton20.setToolTipText("");
        jPanel2.add(jRadioButton20);
        jRadioButton20.setBounds(70, 370, 43, 25);

        jRadioButton21.setText("G2");
        jPanel2.add(jRadioButton21);
        jRadioButton21.setBounds(70, 420, 43, 25);

        jRadioButton22.setText("H2");
        jPanel2.add(jRadioButton22);
        jRadioButton22.setBounds(70, 470, 43, 25);

        jRadioButton23.setText("B3");
        jPanel2.add(jRadioButton23);
        jRadioButton23.setBounds(220, 180, 43, 25);

        jRadioButton24.setText("C3");
        jPanel2.add(jRadioButton24);
        jRadioButton24.setBounds(220, 220, 43, 25);

        jRadioButton25.setText("C4");
        jPanel2.add(jRadioButton25);
        jRadioButton25.setBounds(290, 220, 43, 25);

        jRadioButton26.setText("D4");
        jPanel2.add(jRadioButton26);
        jRadioButton26.setBounds(290, 270, 43, 25);

        jRadioButton27.setText("D3");
        jPanel2.add(jRadioButton27);
        jRadioButton27.setBounds(220, 270, 43, 25);

        jRadioButton28.setText("E3");
        jPanel2.add(jRadioButton28);
        jRadioButton28.setBounds(220, 320, 43, 25);

        jRadioButton29.setText("E4");
        jPanel2.add(jRadioButton29);
        jRadioButton29.setBounds(290, 320, 43, 25);

        jRadioButton30.setText("F3");
        jPanel2.add(jRadioButton30);
        jRadioButton30.setBounds(220, 370, 43, 25);

        jRadioButton31.setText("F4");
        jPanel2.add(jRadioButton31);
        jRadioButton31.setBounds(290, 370, 43, 25);

        jRadioButton32.setText("G3");
        jPanel2.add(jRadioButton32);
        jRadioButton32.setBounds(220, 420, 43, 25);

        jRadioButton33.setText("G4");
        jPanel2.add(jRadioButton33);
        jRadioButton33.setBounds(290, 420, 43, 25);

        jRadioButton34.setText("H4");
        jPanel2.add(jRadioButton34);
        jRadioButton34.setBounds(290, 470, 43, 25);

        jRadioButton35.setText("H3");
        jPanel2.add(jRadioButton35);
        jRadioButton35.setBounds(220, 470, 43, 25);

        jRadioButton36.setText("J3");
        jPanel2.add(jRadioButton36);
        jRadioButton36.setBounds(220, 520, 41, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 130, 350, 570);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("TotalAmmount");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 270, 120, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 560, 110, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TotalSeat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 230, 120, 22);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(560, 580, 150, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(740, 190, 130, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(740, 230, 130, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TotalCost");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 190, 110, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(740, 270, 130, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(880, 500, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(880, 560, 110, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("MobileNo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 480, 110, 22);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(560, 500, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("E-mail");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(880, 480, 110, 22);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(880, 580, 150, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Cancel");
        getContentPane().add(jButton6);
        jButton6.setBounds(890, 630, 100, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Payment");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1020, 630, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Payment P = new Payment();
       P.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
